### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by aledegano** [FortnoxAB/alertmanager2hangoutschat#3]
First of all, thank you so much for sharing this project: it's a life saver!

In order to streamline the deployment of this service it would be very handy if we could directly grab the binary from the releases.

Would it be possible to include the binary in the release page as well, please?

**Comment by MPV** [comment]
And/or publish the docker image onto Docker Hub (or equivalent)?

**Comment by MPV** [comment]
Never mind, found the published docker image now: 👍 
https://quay.io/repository/fortnox/alertmanager2hangoutschat
